In [1]:
#1.create and reshape array

import numpy as np

In [15]:
arr=np.arange(1,21)
arr



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
matrix=arr.reshape(4,5)
print("Matrix:")
(matrix)

Matrix:


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
print("Shape:", matrix.shape)

Shape: (4, 5)


In [27]:
print("Dimension:", matrix.ndim)

Dimension: 2


In [31]:
#2.Array statistics

marks=np.array([78,85,92,67,88,95,72,81,90,76])

print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Maximum", np.max(marks))
print("Minimum", np.min(marks))

Mean: 82.4
Median: 83.0
Maximum 95
Minimum 67


In [51]:
#3.matrix operations

A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

B=np.array([[9,8,7],
            [6,5,4],
            [3,2,1]])

#Addition

print("Addition")
print(A+B)

#Substraction
print("Substraction")
print(A-B)

#Elementwise mulitiplication
print("Elementwise multiplication")
print(A*B)

Addition
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Substraction
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Elementwise multiplication
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [67]:
#4.Real world sales:

sales=np.array([
    12000,15000,18000,14000,
    22000,25000,21000,19000,
    28000,30000,27000,32000
])

print("Total sales", np.sum(sales))
print("Average sales", np.average(sales))
print("Highest sales", np.max(sales))
print("Lowest sales", np.min(sales))

Total sales 263000
Average sales 21916.666666666668
Highest sales 32000
Lowest sales 12000
