In [14]:
#1.Create an array 1 to and print it 

import numpy as np

arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#2.Array operations

a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])

#Addition
print("Addition")
print(a+b)

#Substraction
print("Substraction")
print(a-b)

#Multiplication
print("Multiplicaton")
print(a*b)

#Division
print("Division")
print(a/b)

Addition
[11 22 33 44 55]
Substraction
[ 9 18 27 36 45]
Multiplicaton
[ 10  40  90 160 250]
Division
[10. 10. 10. 10. 10.]


In [11]:
#3.find maximum and minimum

marks=np.array([85,72,91,65,78,88])

print("Maximum Mark:", np.max(marks))
print("Minimum Mark", np.min(marks))
print("Average mark:", np.average(marks))

Maximum Mark: 91
Minimum Mark 65
Average mark: 79.83333333333333


In [20]:
#4.create array 1 to 20 only even numbers

arr=np.arange(1,21)
arr1=arr[arr %2==0]
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
#5.reshape an array 

arr=np.arange(1,13)
arr1=arr.reshape(3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])